<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <title> Noticias </title>
        <style type="text/css">body { font-family: Arial; }</style>
  </head>
  <body>
   <h1> Notícias </h1>
   <a href="/">Home</a> | <a href="/s/in">Login</a> | <a href="/s/up">Cadastro</a>
   <h2> Cadastre-se </h2>
   
   <form method="post" action="/s/up">
    <label>Nome</label>
    <input type="text" name="name" id="name" />
    <br />
    <label>Email(utilizado para acessar)</label>
    <input type="text" name="email" id="email" />
    <br />
    <label>Senha(utilizado para acessar)</label>
    <input type="password" name="password" id="password" />
    <br />
    <input type="submit" value="Cadastrar" />
   </form> 
   
   </body>
</html>
